sonar.projectKey=psmpaulamelo_cafeteria-legal
sonar.organization=psmpaulamelo

sonar.sources=backend/src,frontend/app,frontend/components,frontend/context,frontend/services

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**